### ISSUE TITLE
Dependencies are too rigid

### ISSUE THREAD

**Issue by AmitMY** [danielkelshaw/PyGA#51]
the strong `==` in the dependencies makes installing this package quite difficult

**Comment by danielkelshaw** [comment]
Developed this package a long time ago and have no real intention of maintaining it.
Please feel free to submit a pull request and I'd be happy to merge it in.

**Comment by danielkelshaw** [comment]
Resolved in [f46b52e](https://github.com/danielkelshaw/PyGA/commit/f46b52ecd8984795ca26adf5a2a9c3abcd8f1205)

Thanks @AmitMY
